In [1]:
import numpy as np
from numpy.linalg import inv

In [2]:
x = [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013]

y = [2.000, 2.500, 2.900, 3.147, 4.515, 4.903, 5.365, 5.704, 6.853, 7.971, 8.561, 10.000, 11.280, 12.900]


In [26]:
X = np.c_[np.ones_like(x), x].astype('float')
y = np.array(y).astype('float')

# Close-form solution

$$
\theta = (X^TX)^{-1} X^T y
$$

In [27]:
theta = inv(X.T @ X) @ X.T @ y

In [28]:
theta

array([-1.59687382e+03,  7.99004396e-01])

# Gradient descent solution

In [29]:
alpha = 0.0000001

p = np.zeros(2)
#p = theta.copy()
for i in range(100):
    error = np.expand_dims(X @ p - y, axis=1)
    #print(np.sum(error * X, axis=0))
    p = p - alpha * np.sum(error * X, axis=0)
    #print('p',p)


In [30]:
p

array([-6.54233331e+60, -1.31272448e+64])

In [31]:
alpha = 0.00000003

p = np.zeros(2)
#p = theta.copy()
for i in range(100000):
    error = np.expand_dims(X @ p - y, axis=1)
    #print(np.sum(error * X, axis=0))
    p = p - alpha * np.sum(error * X, axis=0)
    #print('p',p)
p

array([-0.00026913,  0.00315735])

In [9]:
p

array([1.48325093e-06, 3.15721098e-03])

There're some numerical problem.

In [10]:
X_s = X.copy() # standardized X
mean,std = X[:,1].mean(), X[:,1].std()
X_s[:,1] = (X[:,1] - mean)/std

In [11]:
alpha = 0.1

p = np.zeros(2)
for i in range(10000):
    error = np.expand_dims(X_s @ p - y, axis=1)
    p = p - alpha * np.sum(error * X_s, axis=0)


In [12]:
mean,std

(2006.5, 4.031128874149275)

In [13]:
p

array([6.3285    , 3.22088969])

$$
y = \theta_0' + \theta_1' X' = \theta_0' + \theta_1' \frac{X - \bar{X}}{\mathrm{sd}(X)} =
\theta_0' -  \frac{\theta_1'\bar{X}}{\mathrm{sd}(X)} + \frac{\theta_1'}{\mathrm{sd}(X)}X
$$

In [14]:
p[0] - p[1] * mean/std, p[1]/std

(-1596.8738197802197, 0.7990043956043956)

# statsmodels consistent check

In [15]:
import statsmodels.api as sm

In [16]:
model = sm.OLS(y, X)
res = model.fit()
res.summary()

D:\anaconda\lib\site-packages\scipy\stats\stats.py:1394: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  "anyway, n=%i" % int(n))


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.962
Model:                            OLS   Adj. R-squared:                  0.958
Method:                 Least Squares   F-statistic:                     300.0
Date:                Wed, 19 Sep 2018   Prob (F-statistic):           7.43e-10
Time:                        23:03:48   Log-Likelihood:                -13.709
No. Observations:                  14   AIC:                             31.42
Df Residuals:                      12   BIC:                             32.70
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1596.8738     92.565    -17.251      0.000   -1798.557   -1395.191
x1             0.7990      0.046     17.320      0.000       0.698       0.900
==============================================================================
Omnibus:                        0.863   Durbin-Watson:                   0.508
Prob(Omnibus):                  0.650   Jarque-Bera (JB):                0.700
Skew:                           0.475   Prob(JB):                        0.705
Kurtosis:                       2.453   Cond. No.                     9.99e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.99e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [17]:
res.params

array([-1.59687382e+03,  7.99004396e-01])