In [1]:
import numpy as np
from numpy.linalg import inv

In [11]:
import statsmodels.api as sm

In [9]:
x = np.arange(10)
X = np.c_[np.ones_like(x), x]
beta = np.array([1,2])
y = X @ beta + np.random.randn(X.shape[0])


In [10]:
y

array([ 0.47134019,  1.69442827,  5.50017593,  6.5750285 ,  9.76012454,
       10.34238904, 11.43953863, 14.41969177, 17.21147141, 18.5917079 ])

In [12]:
sm.OLS(y, X).fit().summary()

D:\anaconda\lib\site-packages\scipy\stats\stats.py:1394: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.986
Model:                            OLS   Adj. R-squared:                  0.984
Method:                 Least Squares   F-statistic:                     554.2
Date:                Mon, 10 Sep 2018   Prob (F-statistic):           1.13e-08
Time:                        19:04:49   Log-Likelihood:                -10.526
No. Observations:                  10   AIC:                             25.05
Df Residuals:                       8   BIC:                             25.66
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.5603      0.456      1.230      0.254      -0.490       1.611
x1             2.0089      0.085     23.541      0.000       1.812       2.206
==============================================================================
Omnibus:                        0.033   Durbin-Watson:                   2.272
Prob(Omnibus):                  0.984   Jarque-Bera (JB):                0.252
Skew:                           0.072   Prob(JB):                        0.882
Kurtosis:                       2.236   Cond. No.                         10.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [22]:
inv(X.T @ X) @ X.T @ y

array([0.56033547, 2.00894537])

In [29]:
alpha = 0.001 

p = np.zeros(2)
#p = theta.copy()
for i in range(1000):
    error = np.expand_dims(X @ p - y, axis=1)
    #print(np.sum(error * X, axis=0))
    p = p - alpha * np.sum(error * X, axis=0)
    #print('p',p)


In [30]:
p

array([0.54649323, 2.01115285])